apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-service-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: hello-service-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_VALUE
      remoteRef:
        key: hello-service
        property: secret_value
